### ISSUE TITLE
[Cache] Garbage value in shared region (NS, Realm)

### ISSUE THREAD

**Issue by bitboom** [Samsung/islet#146]
I found that RMM reads dummy values (0xCFDFDFDF) with ACS tests.
- Read failed with ACS: Params 0x88306000
- Read succeed with TFTF: Params 0x88C01000

_Originally posted by @bitboom in https://github.com/Samsung/islet/issues/145#issuecomment-1672644130_

**Comment by jinbpark** [comment]
@bitboom ,
Not sure if [this PR](https://github.com/Samsung/islet/pull/143) helps solving this,
But I added some points to wipe out a page by zero. 
1. a transition from Undelegated to Delegated
2. a transition from Delegated to Undelegated

I think it's worth a try running the same ACS test with this PR. (not that high probability though)

**Comment by bitboom** [comment]
@jinbpark Thank you for the suggestion.

I found the cause of this issue.
The issue is that ACS set the shared region as `Normal, Inner/Outer WB/WA/RA`, but islet map the region as `Device` in `set_pages_for_rmi`.

When i changed ACS to `Device` temporarily, i could read the memory.

But I think our islet should change to `Normal` in `set_pages_for_rmi`. I tried it but failed :(

**Comment by jinbpark** [comment]
> When i changed ACS to Device temporarily, i could read the memory.

This sounds quite likely a TLB issue. (not 100% sure though)
It might be worth trying to run the below code.

```
pub fn set_pages_for_rmi(addr: usize, secure: bool) {
    let device_flags = helper::bits_in_reg(PTDesc::INDX, attr::mair_idx::RMM_MEM);
    ....
    page_table.set_pages(va, phys, PAGE_SIZE, rw_flags | device_flags | secure_flags);
    ....
    unsafe {
        asm!("tlbi alle2", "dsb sy", "isb",);   // TLB flush
    }
}
```

**Comment by bitboom** [comment]
@jinbpark Thanks for the suggestion! I tried it but i does't work :(

The problem seems to relate with cache. When i turn off cache with `cache_state_modelled=0` of acs's script, it work.
Since this is not the tfundamental solution, I detached this issue from origin PR https://github.com/Samsung/islet/pull/148.
