### ISSUE TITLE
The project repository takes a lot of disk space

### ISSUE THREAD

**Issue by p-sawicki2** [Samsung/islet#218]
Currently there is an issue with using submodules that points at subprojects kept as a branches in the islet-asset repository.
The main repository takes about **83GB** disk space, it’s because git duplicates the islet-asset repo for each submodule.
 
```
$ du -sh .git/modules/third-party/*
4.9G    .git/modules/third-party/android-kernel
4.9G    .git/modules/third-party/cca-rmm-acs
4.9G    .git/modules/third-party/gki-build
4.9G    .git/modules/third-party/kvmtool
4.9G    .git/modules/third-party/kvmtool-rim-measurer
4.9G    .git/modules/third-party/kvm-unit-tests
4.9G    .git/modules/third-party/mbedtls
4.9G    .git/modules/third-party/nw-linux
4.9G    .git/modules/third-party/optee-build
4.9G    .git/modules/third-party/realm-linux
4.9G    .git/modules/third-party/tf-a
4.9G    .git/modules/third-party/tf-a-rss
4.9G    .git/modules/third-party/tf-a-tests
4.9G    .git/modules/third-party/tf-rmm 
```
 
This is also the reason why the initialization process (**./scripts/init.sh**) takes a lot of time. I think that if we’re going to make the project more user friendly for potential open source contributors, this should be fixed somehow. The easiest way seems to be keeping these subprojects as separate git repositories. But, I’m not a git/GitHub guru on that matter, and maybe there is a better solution.

**Comment by zpzigi754** [comment]
Good to report this issue with the visualization! I also agree that this huge disk consumption issue should be resolved. 

We've avoided this issue by using only a minimum dependency on ci (e.g., using `init_sh_min.sh` instead of `init.sh`), yet another solution seems to be needed.
