### ISSUE TITLE
rust-rsi issue & SDK problem

### ISSUE THREAD

**Issue by TomaszSwierczek** [Samsung/islet#232]
**Background**

As you are well aware, SRPOL team is trying to make all elements required for remote attestation work with Islet & make them available from within Islet github space.

In may, @Havner was asked to put the linux-rsi elements (driver, library, etc.) into Islet repository - that resulted in two pull requests: 

https://github.com/Samsung/islet/pull/74
https://github.com/Samsung/islet/pull/75

merged into the repository soon after.

Now, as we're moving the remaining components for remote attestation (ratls, realm-verifier, being the biggest ones) into Islet, we've found an issue.

For development needs of remote attestation, linux-rsi needed to be enhanced and was split into rsictl (thin command line tool) and rust-rsi library thats responsible for parsing the attestation tokens and things needed for their management (used by all other remote attestation modules). 

rust-rsi upstream used by remote attestation is here: https://github.com/Havner/rust-rsi/ (we're decided to make it a separate, reusable component).

On the other hand, the linux-rsi merged originally into the Islet repository was split into few crates / submodules:

1. cmd line tools (cli/islet)
2. token parsing (cca-token)
3. ioctl management (rsi-el0)
4. cose / signing (cose)

**Problem**

rust-rsi and linux-rsi elements in Islet are now incompatible - claim format, token formats are changed, which is a result of code paste & modification directly in Islet repository, not being used as an external, separate tool.

**Proposed solution**

A solution to properly structure the project would be to use one common codebase for token/claim management - but there's an obstacle: the SDK module, which we're not familiar with at SRPOL, that we don't want to break, uses the (2) part (cca-token).

What we're proposing is to check what SDK needs from rust-rsi & get it ported to use the upstream provided - we can put it under Samsung space even, if needed.

**Follow-up**

Another point in this topic, is - whether we should really keep some of these modules - rust-rsi, realm-verifier, ratls, etc. as parts within one git repo. If we do, we risk - long-term - modifications & management issues like the mentioned above split of linux-rsi. And in some areas, like Arm-based components, this can result in harder updates from upstream later. I have second thoughts on how should we manage these long-term, considering the now-agreed plan to put attestation components into Islet repository.

@zos @Havner @p-sawicki2 @bokdeuk-jeong  (please add more members if needed for discussion!)

**Comment by bitboom** [comment]
First, thanks to you all related with remote attestation ! 😄 

---

### History
From March, HQ have prepared `Islet SDK` to collaborate with [certifier](https://github.com/vmware-research/certifier-framework-for-confidential-computing) for the demonstration at Confidential Computing Summit.
`Certifier` required the attestation features, getting the report and verifying it, running on x86_64 as simulated version.
When i started to developed the features, there was no `linux-rsi`. So, i made them with the hard-coded report and parsing it using [minicbor](https://crates.io/crates/minicbor).

After `linux-rsi` was merged into `Islet`, I used it to run Islet SDK running on FVP. Recently I removed the duplication of token parsing in https://github.com/Samsung/islet/pull/224.

### About rust-rsi
> What we're proposing is to check what SDK needs from rust-rsi 

`Islet SDK` needs below running on both x86_64 and aarch64:
 - Getting Attestation Token
   -  hard-coded report would be returned but realm challenge could be replaced before verifying it.
 - Verifying Attestation Token
 - Parsing Attestation Token

What i proposing is 
1. SRPOR team: Use `rust-rsi` regardless of current islet components
3. SRPOR team: Done remote attestation porting
4. HQ team: Use `rust-rsi` to `sdk` & remove duplicated component in Islet.
5. HQ team: If additional features needed, make the PR to `rust-rsi`

> we can put it under Samsung space even, if needed.

In my human opinion, `rust-rsi` should be put to `samsung space`.
If you want to make `rust-rsi` as seperate repo, not `islet`, you have to proceed [opensource process](https://opensource.sec.samsung.net/view/process).


### Managing repositories
>## Follow-up
>Another point in this topic, is - whether we should really keep some of these modules - rust-rsi, realm-verifier, ratls, etc. as parts within one git repo

I think the best way is that create our github organization like [gramine](https://github.com/gramineproject), [veracruz](veracruz-project).
- islet-project/islet
- islet-project/rust-rsi
- islet-project/realm-verifier
- ...

AFAIK, there were no cases, making own github org, in samsung. I will check whether it is possible after this year's goal is achieved.

**Comment by TomaszSwierczek** [comment]
@bitboom , thanks a lot for fast response!

Regading the steps:

> SRPOR team: Use rust-rsi regardless of current islet components
> SRPOR team: Done remote attestation porting
> HQ team: Use rust-rsi to sdk & remove duplicated component in Islet.
> HQ team: If additional features needed, make the PR to rust-rsi

@Havner , I think its okay this way, isn't it?

> In my human opinion, rust-rsi should be put to samsung space.
> If you want to make rust-rsi as seperate repo, not islet, you have to proceed [opensource process]> (https://opensource.sec.samsung.net/view/process).

we're not attached that much to having @Havner 's own upstream project, we did it simply because the code was pushed in Islet repo so it was in public domain already and we needed a shared one for our projects, thats all. Since I expect Islet will be our main working repo for CC, I think what we can do is to find a place somewhere under Samsung space to put it - and here we go with...

> I think the best way is that create our github organization like (...)
>
> islet-project/islet
> islet-project/rust-rsi
> islet-project/realm-verifier
> ...

thats precisely what would be the best way IMHO. Can we do this instead of keeping every dependency in single repo? Are there any obstacles - since this will require creating new entity on github and inside of it, some new repos? 

And most importantly for our current work - do we need/want to continue putting these elements (incl. rust-rsi) into Islet *current* repo right now (continuing with the steps I've quoted in beginning of my comment) just to finish adding the remote attestation bits as fast as possible, or can we 1st create proper organization? 

I see this as a long-term project, so I'd be more inclined towards the 2nd approach with creating organization 1st, but I am not fully sure the paperwork & waiting is what we can afford right now. Can someone tell?

**Comment by bitboom** [comment]
HQ team discussed about this at offline. It seems to hard to create our own organization right now.
 (Because of our deadline & we are currently joining [CCC](https://confidentialcomputing.io/) with samsung/islet repo)

## An alternative
How about create another repository in samsung space? 

- samsung/islet: Core components for on-device CC f/w
  - rmm
  - sdk
  - hes
  - scripts/fvp-cca
  - examples/veraison
- samsung/islet-asset
- **(new) samsung/islet-ra (or islet-remote-attestation) : Core modules/libs for remote attestation**
  - ratls
  - rust-rsi
  - realm-verifier
  - ...

Creating one repo in samsung space takes about 1~2 weeks.

**Comment by p-sawicki2** [comment]
The idea with the separate **samsung/islet-ra** repo seems to be fine. So if creating the new repository is going to take a few weeks, the process can be started as soon as possible.

The rest of the plan also looks OK:

> 1.     SRPOL team: Use rust-rsi regardless of current islet components
> 2.     SRPOL team: Done remote attestation porting
> 3.     HQ team: Use rust-rsi to sdk & remove duplicated component in Islet.
> 4.     HQ team: If additional features needed, make the PR to rust-rsi

On Monday, I'm going to prepare more detailed plan.

**Comment by bitboom** [comment]
> So if creating the new repository is going to take a few weeks, the process can be started as soon as possible.

I just started the process to create Islet RA repository.

**Comment by bitboom** [comment]
https://github.com/Samsung/islet-ra is created !
