### ISSUE TITLE
Running islet with --normal-world=linux-net breaks network configuration on the host

### ISSUE THREAD

**Issue by Havner** [Samsung/islet#240]
Following the following readme:
https://github.com/Samsung/islet/blob/main/doc/network.md

Running fvp with the following command breaks network configuration on the host effectively cutting it off the internet.

```./scripts/fvp-cca --normal-world=linux-net --realm=linux --rmm=tf-rmm```

Which is a serious issue when working remotely.

**Comment by Havner** [comment]
Also this line will not work when run from non privileged account:

```sudo echo 1 >/proc/sys/net/ipv4/ip_forward```

I recommend tee(1)

**Comment by jinbpark** [comment]
As you said, creating a tab device on the host side would be enough to enable network between Host<->FVP_Host<->Realm. (I don't remember what my intention was...) If the script you modified works, could you make a PR for that change? I can test it on our side and merge it.

**Comment by Havner** [comment]
https://github.com/Samsung/islet/pull/243
