### ISSUE TITLE
Network is not configured on the realm

### ISSUE THREAD

**Issue by Havner** [Samsung/islet#241]
After locally fixing two issues mentioned in #240 I've managed to get networking on the FVP linux.

Run with:
```./scripts/fvp-cca --normal-world=linux-net --realm=linux --rmm=islet --hes```

then realm with:
```./launch-realm.sh```

According to this file network should be configured on the realm:
https://github.com/Samsung/islet/blob/main/doc/network.md

What I get is:
```
# ip r
default dev eth0 scope link src 169.254.117.165 metric 1001002
169.254.0.0/16 dev eth0 scope link src 169.254.117.165 metric 1002
# ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether 02:15:15:15:15:15 brd ff:ff:ff:ff:ff:ff
    inet 169.254.117.165/16 brd 169.254.255.255 scope global noprefixroute eth0
       valid_lft forever preferred_lft forever
```

The IP addresses here do not match tap interfaces configured on the host and on the FVP and do not match with those from the nerwork readme. The network doesn't work.

**Comment by jinbpark** [comment]
https://github.com/Samsung/islet/commit/89d98659c85f66b57aa2826e299deec74037252a
--> Could you retry with `$ ./launch-realm.sh net` instead of `$ ./launch-realm.sh`?

`$ ./launch-realm.sh net`  --> launch a realm with networking
`$ ./launch-realm.sh` --> launch a realm without networking

We modified the script several months ago, but it seems that we've missed updating `network.md` along with it.

**Comment by bitboom** [comment]
After launching a realm with `./launch-realm.sh net`  as @jinbpark  mentioned, Could you set the realm's ip with below command?

```sh
/shared/set-realm-ip.sh
```

**Comment by zpzigi754** [comment]
> We modified the script several months ago, but it seems that we've missed updating `network.md` along with it.

Oops, it's my fault. Sorry for not updating the document!

**Comment by jinbpark** [comment]
Full script here--

1. Host: `$ ./scripts/fvp-cca --normal-world=linux-net --realm=linux --rmm=tf-rmm`
2. FVP Host: `$ ./launch-realm.sh net`
3. Realm: `$ /shared/set-realm-ip.sh`

I'll update `network.md` after you confirm it works.

**Comment by Havner** [comment]
> Full script here--
> 
>     1. Host: `$ ./scripts/fvp-cca --normal-world=linux-net --realm=linux --rmm=tf-rmm`
> 
>     2. FVP Host: `$ ./launch-realm.sh net`
> 
>     3. Realm: `$ /shared/set-realm-ip.sh`
> 
> 
> I'll update `network.md` after you confirm it works.

Tested with https://github.com/Samsung/islet/pull/243 applied.
Confirmed it does work.
