### ISSUE TITLE
About Launch Realm in FVP

### ISSUE THREAD

**Issue by AuroraHaaash** [Samsung/islet#42]

**Comment by AuroraHaaash** [comment]
Hello，I may have some trouble when launch realm in fvp nw-linux. It seems to take much time to do this.
I wrote a "launch-realm.sh" to run in my NW-Linux, then it stuck at "# sh launch_realm.sh" while output nothing.
SO IS THERE ANY ADVICE TO SOLVE THIS? THX A LOT

**Comment by bitboom** [comment]
Hi, Did you run with `tf-rmm` and `linux-cca`? Normal world linux needs CCA related patches including RMI. And realm needs RSI patches too.
- https://gitlab.arm.com/linux-arm/linux-cca/-/tree/cca-host/rfc-v1
- https://gitlab.arm.com/linux-arm/linux-cca/-/tree/cca-guest/rfc-v1

**Comment by AuroraHaaash** [comment]
FIRSTLY, THX SO MUCH FOR YOUR REPLY! I‘ve recently participated in a project related to ARM CCA, so I may make some mistakes.
I simply used the "https://gitlab.arm.com/linux-arm/linux-cca" for both my nw-linux and realm, and I'm not very sure if it can work properly.
By the way I noticed that the commands in the README file of main-brunch are different from the commands in islet-asset/prebuilt/qemu/guest/run-guest.sh.

**Comment by bitboom** [comment]
README of main branch is outdated :(
_It's about [v0.0.1](https://github.com/Samsung/islet/tree/v0.0.1 which uses nw-linux (5.18) and realm-linux (not modified)_

So, could you refer the description of https://github.com/Samsung/islet/pull/35? 
I will update README soon :)

**Comment by AuroraHaaash** [comment]
sorry for bothering you so much. I 've noticed the differences between https://github.com/Samsung/islet/pull/35 and README file of main-branch before opening this issue.
I'm not sure whether the master-brunch of https://gitlab.arm.com/linux-arm/linux-cca support the RMI and RSI. I want to know "islet" use which branch of "https://gitlab.arm.com/linux-arm/linux-cca" for the nw-linux and realm-linux (i.e. is its master branch does not work properly?)
[nw-linux]
branch = "3rd-nw-linux-230222"
commit = "604bc2c405be"
upstream = "upstream-linux-cca-rfc-v1"

[realm-linux]
branch = "3rd-realm-linux-230222"
commit = "c0517c7c4c7a"
upstream = "upstream-linux-cca-rfc-v1"

**Comment by AuroraHaaash** [comment]
it may finally worked when i used linux-cca-full for nw-linux and realm linux, but im not very sure cuz it didn't open 4 terminals as it run with tf-test(only 3 terminals), is the realm linux shell in the same fvp terminal of normal world?

**Comment by bitboom** [comment]
>  is the realm linux shell in the same fvp terminal of normal world?

Yes, you're right!

**Comment by AuroraHaaash** [comment]
And the last problem is how to exit from realm linux to nw-linux... it seems that directly using "exit" command would result in kernel panic.
ANY WAY THANK YOU SO MUCH FOR HELP!!! now i'm able to continue my work on rmm, REALLY THX

**Comment by bitboom** [comment]
> And the last problem is how to exit from realm linux to nw-linux...

AFAIK, there is no way to exit from realm to nw-linux for now :(
