### ISSUE TITLE
RMI status

### ISSUE THREAD

**Issue by bitboom** [Samsung/islet#48]
| FID        | RMM Spec                  | Islet supported |
| ---------- | ------------------------- | --------------- |
| 0xC4000150 | RMI_VERSION               | O               |
| 0xC4000151 | RMI_GRANULE_DELEGATE      | O               |
| 0xC4000152 | RMI_GRANULE_UNDELEGATE    | O               |
| 0xC4000153 | RMI_DATA_CREATE           | X               |
| 0xC4000154 | RMI_DATA_CREATE_UNKNOWN   | X               |
| 0xC4000155 | RMI_DATA_DESTROY          | X               |
| 0xC4000157 | RMI_REALM_ACTIVATE        | X               |
| 0xC4000158 | RMI_REALM_CREATE          | O               |
| 0xC4000159 | RMI_REALM_DESTROY         | X               |
| 0xC400015A | RMI_REC_CREATE            | X               |
| 0xC400015B | RMI_REC_DESTROY           | X               |
| 0xC400015C | RMI_REC_ENTER             | X               |
| 0xC400015D | RMI_RTT_CREATE            | X               |
| 0xC400015E | RMI_RTT_DESTROY           | X               |
| 0xC400015F | RMI_RTT_MAP_UNPROTECTED   | X               |
| 0xC4000161 | RMI_RTT_READ_ENTRY        | X               |
| 0xC4000162 | RMI_RTT_UNMAP_UNPROTECTED | X               |
| 0xC4000164 | RMI_PSCI_COMPLETE         | X               |
| 0xC4000165 | RMI_FEATURES              | O               |
| 0xC4000166 | RMI_RTT_FOLD              | X               |
| 0xC4000167 | RMI_REC_AUX_COUNT         | O               |
| 0xC4000168 | RMI_RTT_INIT_RIPAS        | X               |
| 0xC4000169 | RMI_RTT_SET_RIPAS         | X               |

**Comment by bitboom** [comment]
Added RMI_FEATURES, RMI_REX_AUX_COUNT https://github.com/Samsung/islet/pull/45

**Comment by bitboom** [comment]
Some commands are added https://github.com/Samsung/islet/pull/52

**Comment by p-sawicki2** [comment]
Hi,

I wonder if this project could help you in checking the conformance with the RMM specification
https://github.com/ARM-software/cca-rmm-acs

**Comment by jinbpark** [comment]
> I wonder if this project could help you in checking the conformance with the RMM specification https://github.com/ARM-software/cca-rmm-acs

@p-sawicki2 I had a quick look at this repo. It obviously seems to have a rich set of validation testing than that of tf-a-test which we rely on. Thanks for letting us know! It would definitely be helpful:

**Comment by bitboom** [comment]
I tested acs with tf-rmm. Result : 11/19 (passed/total)
Currently our rmm does not work with acs.

```sh
Suite=command : cmd_granule_delegate
Suite=command : cmd_granule_undelegate
Suite=command : cmd_realm_create
Suite=command : cmd_realm_activate
Suite=command : cmd_rtt_read_entry
Suite=command : cmd_rtt_init_ripas
Suite=command : cmd_rtt_create
Suite=command : cmd_data_create
Suite=command : cmd_rtt_map_unprotected
Suite=command : cmd_rec_create
Suite=command : cmd_rec_enter
Suite=command : cmd_rmi_version
Suite=command : cmd_multithread_realm_up
Suite=command : cmd_multithread_realm_mp
Suite=command : cmd_rsi_version
Suite=command : cmd_data_create_unknown
Suite=command : cmd_secure_test
Suite=command : cmd_realm_config
Suite=command : cmd_ipa_state_get
```

**Comment by bitboom** [comment]
replaced: https://github.com/Samsung/islet/issues/149
